# Norlab-MPPI barebones_mpc config CartPole-v1
---
config_name: 'CartPole-v1 discrete sampler random'
config_short_description: "gym CartPole-v1 Discrete hyper parma tunning"
controler_component:
  nominalPath: src.barebones_mpc.nominal_path.random_NP.RandomNominalPath
  model: src.barebones_mpc.model.inv_pendulum_model.InvPendulumModel
  sampler: src.barebones_mpc.sampler.discrete_sampler_rdm.DiscreteSamplerRandom
  evaluator: src.barebones_mpc.evaluator.quadratic_evaluator.QuadraticEvaluator
  selector: src.barebones_mpc.selector.greedy_selector.GreedySelector
force_headless_mode: true
record: false
environment:
  type: 'gym'
  name: 'CartPole-v1'
  rendering_interval: 1
  observation_space:
    dim: 4
    cart_position: 4.8
    cart_velocity: Inf
    pole_angle: 0.418
    pole_angular_velocity: Inf
  input_space:
    type: discrete
    dim: 1
    legal_actions: [0, 1]
hparam:
  controler:
    state_t0: ~
  nominal_path_bootstrap: ~
  experimental_hparam:
    experimental_window: 300
    seed: 0
    show_plot: true
  sampler_hparam:
    number_samples: 500
    horizon: 0.9
    prediction_step: 0.05
  model_hparam:
    cart_mass: 1
    pendulum_mass: 3
  evaluator_hparam:
    std_dev: 0.25
    beta: 0.01
    inverse_temperature: 0.01
    state_weights: 4
  selector_hparam: ~
constraints:
  input_constraint:
    input_space_dim:
      uper_bound: 1
      lowwer_bound: 0
  state-constraint:
    <state-space-1-placeholder>:
      uper_bound: 1.0
      lowwer_bound: -1.0
experimental_notes: |
  Nothing for now
